// Request invite related actions
export const SET_REGISTRATION_STATUS = 'SET_REGISTRATION_STATUS'
export const RESET_REGISTRATION_STATUS = 'RESET_REGISTRATION_STATUS'
export const TOGGLE_REQUEST_SENDING_STATUS = 'TOGGLE_REQUEST_SENDING_STATUS'
export const TOGGLE_REQUEST_INVITE_FORM_VISIBILITY = 'TOGGLE_REQUEST_INVITE_FORM_VISIBILITY'